use_frameworks!

platform :ios, '8.0'

target 'SVPullToRefresh-JM_Example' do
  pod 'SVPullToRefresh-JM', :path => '../'

  target 'SVPullToRefresh-JM_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
